export enum Blocks {
    AIR = "air",
    STONE = "stone",
    GRANITE = "granite",
    POLISHED_GRANITE = "polished_granite",
    DIORITE = "diorite",
    POLISHED_DIORITE = "polished_diorite",
    ANDESITE = "andesite",
    POLISHED_ANDESITE = "polished_andesite",
    GRASS_BLOCK = "grass_block",
    DIRT = "dirt",
    COARSE_DIRT = "coarse_dirt",
    PODZOL = "podzol",
    COBBLESTONE = "cobblestone",
    OAK_PLANKS = "oak_planks",
    SPRUCE_PLANKS = "spruce_planks",
    BIRCH_PLANKS = "birch_planks",
    JUNGLE_PLANKS = "jungle_planks",
    ACACIA_PLANKS = "acacia_planks",
    DARK_OAK_PLANKS = "dark_oak_planks",
    OAK_SAPLING = "oak_sapling",
    SPRUCE_SAPLING = "spruce_sapling",
    BIRCH_SAPLING = "birch_sapling",
    JUNGLE_SAPLING = "jungle_sapling",
    ACACIA_SAPLING = "acacia_sapling",
    DARK_OAK_SAPLING = "dark_oak_sapling",
    BEDROCK = "bedrock",
    WATER = "water",
    LAVA = "lava",
    SAND = "sand",
    RED_SAND = "red_sand",
    GRAVEL = "gravel",
    GOLD_ORE = "gold_ore",
    DEEPSLATE_GOLD_ORE = "deepslate_gold_ore",
    IRON_ORE = "iron_ore",
    DEEPSLATE_IRON_ORE = "deepslate_iron_ore",
    COAL_ORE = "coal_ore",
    DEEPSLATE_COAL_ORE = "deepslate_coal_ore",
    NETHER_GOLD_ORE = "nether_gold_ore",
    OAK_LOG = "oak_log",
    SPRUCE_LOG = "spruce_log",
    BIRCH_LOG = "birch_log",
    JUNGLE_LOG = "jungle_log",
    ACACIA_LOG = "acacia_log",
    DARK_OAK_LOG = "dark_oak_log",
    STRIPPED_SPRUCE_LOG = "stripped_spruce_log",
    STRIPPED_BIRCH_LOG = "stripped_birch_log",
    STRIPPED_JUNGLE_LOG = "stripped_jungle_log",
    STRIPPED_ACACIA_LOG = "stripped_acacia_log",
    STRIPPED_DARK_OAK_LOG = "stripped_dark_oak_log",
    STRIPPED_OAK_LOG = "stripped_oak_log",
    OAK_WOOD = "oak_wood",
    SPRUCE_WOOD = "spruce_wood",
    BIRCH_WOOD = "birch_wood",
    JUNGLE_WOOD = "jungle_wood",
    ACACIA_WOOD = "acacia_wood",
    DARK_OAK_WOOD = "dark_oak_wood",
    STRIPPED_OAK_WOOD = "stripped_oak_wood",
    STRIPPED_SPRUCE_WOOD = "stripped_spruce_wood",
    STRIPPED_BIRCH_WOOD = "stripped_birch_wood",
    STRIPPED_JUNGLE_WOOD = "stripped_jungle_wood",
    STRIPPED_ACACIA_WOOD = "stripped_acacia_wood",
    STRIPPED_DARK_OAK_WOOD = "stripped_dark_oak_wood",
    OAK_LEAVES = "oak_leaves",
    SPRUCE_LEAVES = "spruce_leaves",
    BIRCH_LEAVES = "birch_leaves",
    JUNGLE_LEAVES = "jungle_leaves",
    ACACIA_LEAVES = "acacia_leaves",
    DARK_OAK_LEAVES = "dark_oak_leaves",
    AZALEA_LEAVES = "azalea_leaves",
    FLOWERING_AZALEA_LEAVES = "flowering_azalea_leaves",
    SPONGE = "sponge",
    WET_SPONGE = "wet_sponge",
    GLASS = "glass",
    LAPIS_ORE = "lapis_ore",
    DEEPSLATE_LAPIS_ORE = "deepslate_lapis_ore",
    LAPIS_BLOCK = "lapis_block",
    DISPENSER = "dispenser",
    SANDSTONE = "sandstone",
    CHISELED_SANDSTONE = "chiseled_sandstone",
    CUT_SANDSTONE = "cut_sandstone",
    NOTE_BLOCK = "note_block",
    WHITE_BED = "white_bed",
    ORANGE_BED = "orange_bed",
    MAGENTA_BED = "magenta_bed",
    LIGHT_BLUE_BED = "light_blue_bed",
    YELLOW_BED = "yellow_bed",
    LIME_BED = "lime_bed",
    PINK_BED = "pink_bed",
    GRAY_BED = "gray_bed",
    LIGHT_GRAY_BED = "light_gray_bed",
    CYAN_BED = "cyan_bed",
    PURPLE_BED = "purple_bed",
    BLUE_BED = "blue_bed",
    BROWN_BED = "brown_bed",
    GREEN_BED = "green_bed",
    RED_BED = "red_bed",
    BLACK_BED = "black_bed",
    POWERED_RAIL = "powered_rail",
    DETECTOR_RAIL = "detector_rail",
    STICKY_PISTON = "sticky_piston",
    COBWEB = "cobweb",
    GRASS = "grass",
    FERN = "fern",
    DEAD_BUSH = "dead_bush",
    SEAGRASS = "seagrass",
    TALL_SEAGRASS = "tall_seagrass",
    PISTON = "piston",
    PISTON_HEAD = "piston_head",
    WHITE_WOOL = "white_wool",
    ORANGE_WOOL = "orange_wool",
    MAGENTA_WOOL = "magenta_wool",
    LIGHT_BLUE_WOOL = "light_blue_wool",
    YELLOW_WOOL = "yellow_wool",
    LIME_WOOL = "lime_wool",
    PINK_WOOL = "pink_wool",
    GRAY_WOOL = "gray_wool",
    LIGHT_GRAY_WOOL = "light_gray_wool",
    CYAN_WOOL = "cyan_wool",
    PURPLE_WOOL = "purple_wool",
    BLUE_WOOL = "blue_wool",
    BROWN_WOOL = "brown_wool",
    GREEN_WOOL = "green_wool",
    RED_WOOL = "red_wool",
    BLACK_WOOL = "black_wool",
    MOVING_PISTON = "moving_piston",
    DANDELION = "dandelion",
    POPPY = "poppy",
    BLUE_ORCHID = "blue_orchid",
    ALLIUM = "allium",
    AZURE_BLUET = "azure_bluet",
    RED_TULIP = "red_tulip",
    ORANGE_TULIP = "orange_tulip",
    WHITE_TULIP = "white_tulip",
    PINK_TULIP = "pink_tulip",
    OXEYE_DAISY = "oxeye_daisy",
    CORNFLOWER = "cornflower",
    WITHER_ROSE = "wither_rose",
    LILY_OF_THE_VALLEY = "lily_of_the_valley",
    BROWN_MUSHROOM = "brown_mushroom",
    RED_MUSHROOM = "red_mushroom",
    GOLD_BLOCK = "gold_block",
    IRON_BLOCK = "iron_block",
    BRICKS = "bricks",
    TNT = "tnt",
    BOOKSHELF = "bookshelf",
    MOSSY_COBBLESTONE = "mossy_cobblestone",
    OBSIDIAN = "obsidian",
    TORCH = "torch",
    WALL_TORCH = "wall_torch",
    FIRE = "fire",
    SOUL_FIRE = "soul_fire",
    SPAWNER = "spawner",
    OAK_STAIRS = "oak_stairs",
    CHEST = "chest",
    REDSTONE_WIRE = "redstone_wire",
    DIAMOND_ORE = "diamond_ore",
    DEEPSLATE_DIAMOND_ORE = "deepslate_diamond_ore",
    DIAMOND_BLOCK = "diamond_block",
    CRAFTING_TABLE = "crafting_table",
    WHEAT = "wheat",
    FARMLAND = "farmland",
    FURNACE = "furnace",
    OAK_SIGN = "oak_sign",
    SPRUCE_SIGN = "spruce_sign",
    BIRCH_SIGN = "birch_sign",
    ACACIA_SIGN = "acacia_sign",
    JUNGLE_SIGN = "jungle_sign",
    DARK_OAK_SIGN = "dark_oak_sign",
    OAK_DOOR = "oak_door",
    LADDER = "ladder",
    RAIL = "rail",
    COBBLESTONE_STAIRS = "cobblestone_stairs",
    OAK_WALL_SIGN = "oak_wall_sign",
    SPRUCE_WALL_SIGN = "spruce_wall_sign",
    BIRCH_WALL_SIGN = "birch_wall_sign",
    ACACIA_WALL_SIGN = "acacia_wall_sign",
    JUNGLE_WALL_SIGN = "jungle_wall_sign",
    DARK_OAK_WALL_SIGN = "dark_oak_wall_sign",
    LEVER = "lever",
    STONE_PRESSURE_PLATE = "stone_pressure_plate",
    IRON_DOOR = "iron_door",
    OAK_PRESSURE_PLATE = "oak_pressure_plate",
    SPRUCE_PRESSURE_PLATE = "spruce_pressure_plate",
    BIRCH_PRESSURE_PLATE = "birch_pressure_plate",
    JUNGLE_PRESSURE_PLATE = "jungle_pressure_plate",
    ACACIA_PRESSURE_PLATE = "acacia_pressure_plate",
    DARK_OAK_PRESSURE_PLATE = "dark_oak_pressure_plate",
    REDSTONE_ORE = "redstone_ore",
    DEEPSLATE_REDSTONE_ORE = "deepslate_redstone_ore",
    REDSTONE_TORCH = "redstone_torch",
    REDSTONE_WALL_TORCH = "redstone_wall_torch",
    STONE_BUTTON = "stone_button",
    SNOW = "snow",
    ICE = "ice",
    SNOW_BLOCK = "snow_block",
    CACTUS = "cactus",
    CLAY = "clay",
    SUGAR_CANE = "sugar_cane",
    JUKEBOX = "jukebox",
    OAK_FENCE = "oak_fence",
    PUMPKIN = "pumpkin",
    NETHERRACK = "netherrack",
    SOUL_SAND = "soul_sand",
    SOUL_SOIL = "soul_soil",
    BASALT = "basalt",
    POLISHED_BASALT = "polished_basalt",
    SOUL_TORCH = "soul_torch",
    SOUL_WALL_TORCH = "soul_wall_torch",
    GLOWSTONE = "glowstone",
    NETHER_PORTAL = "nether_portal",
    CARVED_PUMPKIN = "carved_pumpkin",
    JACK_O_LANTERN = "jack_o_lantern",
    CAKE = "cake",
    REPEATER = "repeater",
    WHITE_STAINED_GLASS = "white_stained_glass",
    ORANGE_STAINED_GLASS = "orange_stained_glass",
    MAGENTA_STAINED_GLASS = "magenta_stained_glass",
    LIGHT_BLUE_STAINED_GLASS = "light_blue_stained_glass",
    YELLOW_STAINED_GLASS = "yellow_stained_glass",
    LIME_STAINED_GLASS = "lime_stained_glass",
    PINK_STAINED_GLASS = "pink_stained_glass",
    GRAY_STAINED_GLASS = "gray_stained_glass",
    LIGHT_GRAY_STAINED_GLASS = "light_gray_stained_glass",
    CYAN_STAINED_GLASS = "cyan_stained_glass",
    PURPLE_STAINED_GLASS = "purple_stained_glass",
    BLUE_STAINED_GLASS = "blue_stained_glass",
    BROWN_STAINED_GLASS = "brown_stained_glass",
    GREEN_STAINED_GLASS = "green_stained_glass",
    RED_STAINED_GLASS = "red_stained_glass",
    BLACK_STAINED_GLASS = "black_stained_glass",
    OAK_TRAPDOOR = "oak_trapdoor",
    SPRUCE_TRAPDOOR = "spruce_trapdoor",
    BIRCH_TRAPDOOR = "birch_trapdoor",
    JUNGLE_TRAPDOOR = "jungle_trapdoor",
    ACACIA_TRAPDOOR = "acacia_trapdoor",
    DARK_OAK_TRAPDOOR = "dark_oak_trapdoor",
    STONE_BRICKS = "stone_bricks",
    MOSSY_STONE_BRICKS = "mossy_stone_bricks",
    CRACKED_STONE_BRICKS = "cracked_stone_bricks",
    CHISELED_STONE_BRICKS = "chiseled_stone_bricks",
    INFESTED_STONE = "infested_stone",
    INFESTED_COBBLESTONE = "infested_cobblestone",
    INFESTED_STONE_BRICKS = "infested_stone_bricks",
    INFESTED_MOSSY_STONE_BRICKS = "infested_mossy_stone_bricks",
    INFESTED_CRACKED_STONE_BRICKS = "infested_cracked_stone_bricks",
    INFESTED_CHISELED_STONE_BRICKS = "infested_chiseled_stone_bricks",
    BROWN_MUSHROOM_BLOCK = "brown_mushroom_block",
    RED_MUSHROOM_BLOCK = "red_mushroom_block",
    MUSHROOM_STEM = "mushroom_stem",
    IRON_BARS = "iron_bars",
    CHAIN = "chain",
    GLASS_PANE = "glass_pane",
    MELON = "melon",
    ATTACHED_PUMPKIN_STEM = "attached_pumpkin_stem",
    ATTACHED_MELON_STEM = "attached_melon_stem",
    PUMPKIN_STEM = "pumpkin_stem",
    MELON_STEM = "melon_stem",
    VINE = "vine",
    GLOW_LICHEN = "glow_lichen",
    OAK_FENCE_GATE = "oak_fence_gate",
    BRICK_STAIRS = "brick_stairs",
    STONE_BRICK_STAIRS = "stone_brick_stairs",
    MYCELIUM = "mycelium",
    LILY_PAD = "lily_pad",
    NETHER_BRICKS = "nether_bricks",
    NETHER_BRICK_FENCE = "nether_brick_fence",
    NETHER_BRICK_STAIRS = "nether_brick_stairs",
    NETHER_WART = "nether_wart",
    ENCHANTING_TABLE = "enchanting_table",
    BREWING_STAND = "brewing_stand",
    CAULDRON = "cauldron",
    WATER_CAULDRON = "water_cauldron",
    LAVA_CAULDRON = "lava_cauldron",
    POWDER_SNOW_CAULDRON = "powder_snow_cauldron",
    END_PORTAL = "end_portal",
    END_PORTAL_FRAME = "end_portal_frame",
    END_STONE = "end_stone",
    DRAGON_EGG = "dragon_egg",
    REDSTONE_LAMP = "redstone_lamp",
    COCOA = "cocoa",
    SANDSTONE_STAIRS = "sandstone_stairs",
    EMERALD_ORE = "emerald_ore",
    DEEPSLATE_EMERALD_ORE = "deepslate_emerald_ore",
    ENDER_CHEST = "ender_chest",
    TRIPWIRE_HOOK = "tripwire_hook",
    TRIPWIRE = "tripwire",
    EMERALD_BLOCK = "emerald_block",
    SPRUCE_STAIRS = "spruce_stairs",
    BIRCH_STAIRS = "birch_stairs",
    JUNGLE_STAIRS = "jungle_stairs",
    COMMAND_BLOCK = "command_block",
    BEACON = "beacon",
    COBBLESTONE_WALL = "cobblestone_wall",
    MOSSY_COBBLESTONE_WALL = "mossy_cobblestone_wall",
    FLOWER_POT = "flower_pot",
    POTTED_OAK_SAPLING = "potted_oak_sapling",
    POTTED_SPRUCE_SAPLING = "potted_spruce_sapling",
    POTTED_BIRCH_SAPLING = "potted_birch_sapling",
    POTTED_JUNGLE_SAPLING = "potted_jungle_sapling",
    POTTED_ACACIA_SAPLING = "potted_acacia_sapling",
    POTTED_DARK_OAK_SAPLING = "potted_dark_oak_sapling",
    POTTED_FERN = "potted_fern",
    POTTED_DANDELION = "potted_dandelion",
    POTTED_POPPY = "potted_poppy",
    POTTED_BLUE_ORCHID = "potted_blue_orchid",
    POTTED_ALLIUM = "potted_allium",
    POTTED_AZURE_BLUET = "potted_azure_bluet",
    POTTED_RED_TULIP = "potted_red_tulip",
    POTTED_ORANGE_TULIP = "potted_orange_tulip",
    POTTED_WHITE_TULIP = "potted_white_tulip",
    POTTED_PINK_TULIP = "potted_pink_tulip",
    POTTED_OXEYE_DAISY = "potted_oxeye_daisy",
    POTTED_CORNFLOWER = "potted_cornflower",
    POTTED_LILY_OF_THE_VALLEY = "potted_lily_of_the_valley",
    POTTED_WITHER_ROSE = "potted_wither_rose",
    POTTED_RED_MUSHROOM = "potted_red_mushroom",
    POTTED_BROWN_MUSHROOM = "potted_brown_mushroom",
    POTTED_DEAD_BUSH = "potted_dead_bush",
    POTTED_CACTUS = "potted_cactus",
    CARROTS = "carrots",
    POTATOES = "potatoes",
    OAK_BUTTON = "oak_button",
    SPRUCE_BUTTON = "spruce_button",
    BIRCH_BUTTON = "birch_button",
    JUNGLE_BUTTON = "jungle_button",
    ACACIA_BUTTON = "acacia_button",
    DARK_OAK_BUTTON = "dark_oak_button",
    SKELETON_SKULL = "skeleton_skull",
    SKELETON_WALL_SKULL = "skeleton_wall_skull",
    WITHER_SKELETON_SKULL = "wither_skeleton_skull",
    WITHER_SKELETON_WALL_SKULL = "wither_skeleton_wall_skull",
    ZOMBIE_HEAD = "zombie_head",
    ZOMBIE_WALL_HEAD = "zombie_wall_head",
    PLAYER_HEAD = "player_head",
    PLAYER_WALL_HEAD = "player_wall_head",
    CREEPER_HEAD = "creeper_head",
    CREEPER_WALL_HEAD = "creeper_wall_head",
    DRAGON_HEAD = "dragon_head",
    DRAGON_WALL_HEAD = "dragon_wall_head",
    ANVIL = "anvil",
    CHIPPED_ANVIL = "chipped_anvil",
    DAMAGED_ANVIL = "damaged_anvil",
    TRAPPED_CHEST = "trapped_chest",
    LIGHT_WEIGHTED_PRESSURE_PLATE = "light_weighted_pressure_plate",
    HEAVY_WEIGHTED_PRESSURE_PLATE = "heavy_weighted_pressure_plate",
    COMPARATOR = "comparator",
    DAYLIGHT_DETECTOR = "daylight_detector",
    REDSTONE_BLOCK = "redstone_block",
    NETHER_QUARTZ_ORE = "nether_quartz_ore",
    HOPPER = "hopper",
    QUARTZ_BLOCK = "quartz_block",
    CHISELED_QUARTZ_BLOCK = "chiseled_quartz_block",
    QUARTZ_PILLAR = "quartz_pillar",
    QUARTZ_STAIRS = "quartz_stairs",
    ACTIVATOR_RAIL = "activator_rail",
    DROPPER = "dropper",
    WHITE_TERRACOTTA = "white_terracotta",
    ORANGE_TERRACOTTA = "orange_terracotta",
    MAGENTA_TERRACOTTA = "magenta_terracotta",
    LIGHT_BLUE_TERRACOTTA = "light_blue_terracotta",
    YELLOW_TERRACOTTA = "yellow_terracotta",
    LIME_TERRACOTTA = "lime_terracotta",
    PINK_TERRACOTTA = "pink_terracotta",
    GRAY_TERRACOTTA = "gray_terracotta",
    LIGHT_GRAY_TERRACOTTA = "light_gray_terracotta",
    CYAN_TERRACOTTA = "cyan_terracotta",
    PURPLE_TERRACOTTA = "purple_terracotta",
    BLUE_TERRACOTTA = "blue_terracotta",
    BROWN_TERRACOTTA = "brown_terracotta",
    GREEN_TERRACOTTA = "green_terracotta",
    RED_TERRACOTTA = "red_terracotta",
    BLACK_TERRACOTTA = "black_terracotta",
    WHITE_STAINED_GLASS_PANE = "white_stained_glass_pane",
    ORANGE_STAINED_GLASS_PANE = "orange_stained_glass_pane",
    MAGENTA_STAINED_GLASS_PANE = "magenta_stained_glass_pane",
    LIGHT_BLUE_STAINED_GLASS_PANE = "light_blue_stained_glass_pane",
    YELLOW_STAINED_GLASS_PANE = "yellow_stained_glass_pane",
    LIME_STAINED_GLASS_PANE = "lime_stained_glass_pane",
    PINK_STAINED_GLASS_PANE = "pink_stained_glass_pane",
    GRAY_STAINED_GLASS_PANE = "gray_stained_glass_pane",
    LIGHT_GRAY_STAINED_GLASS_PANE = "light_gray_stained_glass_pane",
    CYAN_STAINED_GLASS_PANE = "cyan_stained_glass_pane",
    PURPLE_STAINED_GLASS_PANE = "purple_stained_glass_pane",
    BLUE_STAINED_GLASS_PANE = "blue_stained_glass_pane",
    BROWN_STAINED_GLASS_PANE = "brown_stained_glass_pane",
    GREEN_STAINED_GLASS_PANE = "green_stained_glass_pane",
    RED_STAINED_GLASS_PANE = "red_stained_glass_pane",
    BLACK_STAINED_GLASS_PANE = "black_stained_glass_pane",
    ACACIA_STAIRS = "acacia_stairs",
    DARK_OAK_STAIRS = "dark_oak_stairs",
    SLIME_BLOCK = "slime_block",
    BARRIER = "barrier",
    LIGHT = "light",
    IRON_TRAPDOOR = "iron_trapdoor",
    PRISMARINE = "prismarine",
    PRISMARINE_BRICKS = "prismarine_bricks",
    DARK_PRISMARINE = "dark_prismarine",
    PRISMARINE_STAIRS = "prismarine_stairs",
    PRISMARINE_BRICK_STAIRS = "prismarine_brick_stairs",
    DARK_PRISMARINE_STAIRS = "dark_prismarine_stairs",
    PRISMARINE_SLAB = "prismarine_slab",
    PRISMARINE_BRICK_SLAB = "prismarine_brick_slab",
    DARK_PRISMARINE_SLAB = "dark_prismarine_slab",
    SEA_LANTERN = "sea_lantern",
    HAY_BLOCK = "hay_block",
    WHITE_CARPET = "white_carpet",
    ORANGE_CARPET = "orange_carpet",
    MAGENTA_CARPET = "magenta_carpet",
    LIGHT_BLUE_CARPET = "light_blue_carpet",
    YELLOW_CARPET = "yellow_carpet",
    LIME_CARPET = "lime_carpet",
    PINK_CARPET = "pink_carpet",
    GRAY_CARPET = "gray_carpet",
    LIGHT_GRAY_CARPET = "light_gray_carpet",
    CYAN_CARPET = "cyan_carpet",
    PURPLE_CARPET = "purple_carpet",
    BLUE_CARPET = "blue_carpet",
    BROWN_CARPET = "brown_carpet",
    GREEN_CARPET = "green_carpet",
    RED_CARPET = "red_carpet",
    BLACK_CARPET = "black_carpet",
    TERRACOTTA = "terracotta",
    COAL_BLOCK = "coal_block",
    PACKED_ICE = "packed_ice",
    SUNFLOWER = "sunflower",
    LILAC = "lilac",
    ROSE_BUSH = "rose_bush",
    PEONY = "peony",
    TALL_GRASS = "tall_grass",
    LARGE_FERN = "large_fern",
    WHITE_BANNER = "white_banner",
    ORANGE_BANNER = "orange_banner",
    MAGENTA_BANNER = "magenta_banner",
    LIGHT_BLUE_BANNER = "light_blue_banner",
    YELLOW_BANNER = "yellow_banner",
    LIME_BANNER = "lime_banner",
    PINK_BANNER = "pink_banner",
    GRAY_BANNER = "gray_banner",
    LIGHT_GRAY_BANNER = "light_gray_banner",
    CYAN_BANNER = "cyan_banner",
    PURPLE_BANNER = "purple_banner",
    BLUE_BANNER = "blue_banner",
    BROWN_BANNER = "brown_banner",
    GREEN_BANNER = "green_banner",
    RED_BANNER = "red_banner",
    BLACK_BANNER = "black_banner",
    WHITE_WALL_BANNER = "white_wall_banner",
    ORANGE_WALL_BANNER = "orange_wall_banner",
    MAGENTA_WALL_BANNER = "magenta_wall_banner",
    LIGHT_BLUE_WALL_BANNER = "light_blue_wall_banner",
    YELLOW_WALL_BANNER = "yellow_wall_banner",
    LIME_WALL_BANNER = "lime_wall_banner",
    PINK_WALL_BANNER = "pink_wall_banner",
    GRAY_WALL_BANNER = "gray_wall_banner",
    LIGHT_GRAY_WALL_BANNER = "light_gray_wall_banner",
    CYAN_WALL_BANNER = "cyan_wall_banner",
    PURPLE_WALL_BANNER = "purple_wall_banner",
    BLUE_WALL_BANNER = "blue_wall_banner",
    BROWN_WALL_BANNER = "brown_wall_banner",
    GREEN_WALL_BANNER = "green_wall_banner",
    RED_WALL_BANNER = "red_wall_banner",
    BLACK_WALL_BANNER = "black_wall_banner",
    RED_SANDSTONE = "red_sandstone",
    CHISELED_RED_SANDSTONE = "chiseled_red_sandstone",
    CUT_RED_SANDSTONE = "cut_red_sandstone",
    RED_SANDSTONE_STAIRS = "red_sandstone_stairs",
    OAK_SLAB = "oak_slab",
    SPRUCE_SLAB = "spruce_slab",
    BIRCH_SLAB = "birch_slab",
    JUNGLE_SLAB = "jungle_slab",
    ACACIA_SLAB = "acacia_slab",
    DARK_OAK_SLAB = "dark_oak_slab",
    STONE_SLAB = "stone_slab",
    SMOOTH_STONE_SLAB = "smooth_stone_slab",
    SANDSTONE_SLAB = "sandstone_slab",
    CUT_SANDSTONE_SLAB = "cut_sandstone_slab",
    PETRIFIED_OAK_SLAB = "petrified_oak_slab",
    COBBLESTONE_SLAB = "cobblestone_slab",
    BRICK_SLAB = "brick_slab",
    STONE_BRICK_SLAB = "stone_brick_slab",
    NETHER_BRICK_SLAB = "nether_brick_slab",
    QUARTZ_SLAB = "quartz_slab",
    RED_SANDSTONE_SLAB = "red_sandstone_slab",
    CUT_RED_SANDSTONE_SLAB = "cut_red_sandstone_slab",
    PURPUR_SLAB = "purpur_slab",
    SMOOTH_STONE = "smooth_stone",
    SMOOTH_SANDSTONE = "smooth_sandstone",
    SMOOTH_QUARTZ = "smooth_quartz",
    SMOOTH_RED_SANDSTONE = "smooth_red_sandstone",
    SPRUCE_FENCE_GATE = "spruce_fence_gate",
    BIRCH_FENCE_GATE = "birch_fence_gate",
    JUNGLE_FENCE_GATE = "jungle_fence_gate",
    ACACIA_FENCE_GATE = "acacia_fence_gate",
    DARK_OAK_FENCE_GATE = "dark_oak_fence_gate",
    SPRUCE_FENCE = "spruce_fence",
    BIRCH_FENCE = "birch_fence",
    JUNGLE_FENCE = "jungle_fence",
    ACACIA_FENCE = "acacia_fence",
    DARK_OAK_FENCE = "dark_oak_fence",
    SPRUCE_DOOR = "spruce_door",
    BIRCH_DOOR = "birch_door",
    JUNGLE_DOOR = "jungle_door",
    ACACIA_DOOR = "acacia_door",
    DARK_OAK_DOOR = "dark_oak_door",
    END_ROD = "end_rod",
    CHORUS_PLANT = "chorus_plant",
    CHORUS_FLOWER = "chorus_flower",
    PURPUR_BLOCK = "purpur_block",
    PURPUR_PILLAR = "purpur_pillar",
    PURPUR_STAIRS = "purpur_stairs",
    END_STONE_BRICKS = "end_stone_bricks",
    BEETROOTS = "beetroots",
    DIRT_PATH = "dirt_path",
    END_GATEWAY = "end_gateway",
    REPEATING_COMMAND_BLOCK = "repeating_command_block",
    CHAIN_COMMAND_BLOCK = "chain_command_block",
    FROSTED_ICE = "frosted_ice",
    MAGMA_BLOCK = "magma_block",
    NETHER_WART_BLOCK = "nether_wart_block",
    RED_NETHER_BRICKS = "red_nether_bricks",
    BONE_BLOCK = "bone_block",
    STRUCTURE_VOID = "structure_void",
    OBSERVER = "observer",
    SHULKER_BOX = "shulker_box",
    WHITE_SHULKER_BOX = "white_shulker_box",
    ORANGE_SHULKER_BOX = "orange_shulker_box",
    MAGENTA_SHULKER_BOX = "magenta_shulker_box",
    LIGHT_BLUE_SHULKER_BOX = "light_blue_shulker_box",
    YELLOW_SHULKER_BOX = "yellow_shulker_box",
    LIME_SHULKER_BOX = "lime_shulker_box",
    PINK_SHULKER_BOX = "pink_shulker_box",
    GRAY_SHULKER_BOX = "gray_shulker_box",
    LIGHT_GRAY_SHULKER_BOX = "light_gray_shulker_box",
    CYAN_SHULKER_BOX = "cyan_shulker_box",
    PURPLE_SHULKER_BOX = "purple_shulker_box",
    BLUE_SHULKER_BOX = "blue_shulker_box",
    BROWN_SHULKER_BOX = "brown_shulker_box",
    GREEN_SHULKER_BOX = "green_shulker_box",
    RED_SHULKER_BOX = "red_shulker_box",
    BLACK_SHULKER_BOX = "black_shulker_box",
    WHITE_GLAZED_TERRACOTTA = "white_glazed_terracotta",
    ORANGE_GLAZED_TERRACOTTA = "orange_glazed_terracotta",
    MAGENTA_GLAZED_TERRACOTTA = "magenta_glazed_terracotta",
    LIGHT_BLUE_GLAZED_TERRACOTTA = "light_blue_glazed_terracotta",
    YELLOW_GLAZED_TERRACOTTA = "yellow_glazed_terracotta",
    LIME_GLAZED_TERRACOTTA = "lime_glazed_terracotta",
    PINK_GLAZED_TERRACOTTA = "pink_glazed_terracotta",
    GRAY_GLAZED_TERRACOTTA = "gray_glazed_terracotta",
    LIGHT_GRAY_GLAZED_TERRACOTTA = "light_gray_glazed_terracotta",
    CYAN_GLAZED_TERRACOTTA = "cyan_glazed_terracotta",
    PURPLE_GLAZED_TERRACOTTA = "purple_glazed_terracotta",
    BLUE_GLAZED_TERRACOTTA = "blue_glazed_terracotta",
    BROWN_GLAZED_TERRACOTTA = "brown_glazed_terracotta",
    GREEN_GLAZED_TERRACOTTA = "green_glazed_terracotta",
    RED_GLAZED_TERRACOTTA = "red_glazed_terracotta",
    BLACK_GLAZED_TERRACOTTA = "black_glazed_terracotta",
    WHITE_CONCRETE = "white_concrete",
    ORANGE_CONCRETE = "orange_concrete",
    MAGENTA_CONCRETE = "magenta_concrete",
    LIGHT_BLUE_CONCRETE = "light_blue_concrete",
    YELLOW_CONCRETE = "yellow_concrete",
    LIME_CONCRETE = "lime_concrete",
    PINK_CONCRETE = "pink_concrete",
    GRAY_CONCRETE = "gray_concrete",
    LIGHT_GRAY_CONCRETE = "light_gray_concrete",
    CYAN_CONCRETE = "cyan_concrete",
    PURPLE_CONCRETE = "purple_concrete",
    BLUE_CONCRETE = "blue_concrete",
    BROWN_CONCRETE = "brown_concrete",
    GREEN_CONCRETE = "green_concrete",
    RED_CONCRETE = "red_concrete",
    BLACK_CONCRETE = "black_concrete",
    WHITE_CONCRETE_POWDER = "white_concrete_powder",
    ORANGE_CONCRETE_POWDER = "orange_concrete_powder",
    MAGENTA_CONCRETE_POWDER = "magenta_concrete_powder",
    LIGHT_BLUE_CONCRETE_POWDER = "light_blue_concrete_powder",
    YELLOW_CONCRETE_POWDER = "yellow_concrete_powder",
    LIME_CONCRETE_POWDER = "lime_concrete_powder",
    PINK_CONCRETE_POWDER = "pink_concrete_powder",
    GRAY_CONCRETE_POWDER = "gray_concrete_powder",
    LIGHT_GRAY_CONCRETE_POWDER = "light_gray_concrete_powder",
    CYAN_CONCRETE_POWDER = "cyan_concrete_powder",
    PURPLE_CONCRETE_POWDER = "purple_concrete_powder",
    BLUE_CONCRETE_POWDER = "blue_concrete_powder",
    BROWN_CONCRETE_POWDER = "brown_concrete_powder",
    GREEN_CONCRETE_POWDER = "green_concrete_powder",
    RED_CONCRETE_POWDER = "red_concrete_powder",
    BLACK_CONCRETE_POWDER = "black_concrete_powder",
    KELP = "kelp",
    KELP_PLANT = "kelp_plant",
    DRIED_KELP_BLOCK = "dried_kelp_block",
    TURTLE_EGG = "turtle_egg",
    DEAD_TUBE_CORAL_BLOCK = "dead_tube_coral_block",
    DEAD_BRAIN_CORAL_BLOCK = "dead_brain_coral_block",
    DEAD_BUBBLE_CORAL_BLOCK = "dead_bubble_coral_block",
    DEAD_FIRE_CORAL_BLOCK = "dead_fire_coral_block",
    DEAD_HORN_CORAL_BLOCK = "dead_horn_coral_block",
    TUBE_CORAL_BLOCK = "tube_coral_block",
    BRAIN_CORAL_BLOCK = "brain_coral_block",
    BUBBLE_CORAL_BLOCK = "bubble_coral_block",
    FIRE_CORAL_BLOCK = "fire_coral_block",
    HORN_CORAL_BLOCK = "horn_coral_block",
    DEAD_TUBE_CORAL = "dead_tube_coral",
    DEAD_BRAIN_CORAL = "dead_brain_coral",
    DEAD_BUBBLE_CORAL = "dead_bubble_coral",
    DEAD_FIRE_CORAL = "dead_fire_coral",
    DEAD_HORN_CORAL = "dead_horn_coral",
    TUBE_CORAL = "tube_coral",
    BRAIN_CORAL = "brain_coral",
    BUBBLE_CORAL = "bubble_coral",
    FIRE_CORAL = "fire_coral",
    HORN_CORAL = "horn_coral",
    DEAD_TUBE_CORAL_FAN = "dead_tube_coral_fan",
    DEAD_BRAIN_CORAL_FAN = "dead_brain_coral_fan",
    DEAD_BUBBLE_CORAL_FAN = "dead_bubble_coral_fan",
    DEAD_FIRE_CORAL_FAN = "dead_fire_coral_fan",
    DEAD_HORN_CORAL_FAN = "dead_horn_coral_fan",
    TUBE_CORAL_FAN = "tube_coral_fan",
    BRAIN_CORAL_FAN = "brain_coral_fan",
    BUBBLE_CORAL_FAN = "bubble_coral_fan",
    FIRE_CORAL_FAN = "fire_coral_fan",
    HORN_CORAL_FAN = "horn_coral_fan",
    DEAD_TUBE_CORAL_WALL_FAN = "dead_tube_coral_wall_fan",
    DEAD_BRAIN_CORAL_WALL_FAN = "dead_brain_coral_wall_fan",
    DEAD_BUBBLE_CORAL_WALL_FAN = "dead_bubble_coral_wall_fan",
    DEAD_FIRE_CORAL_WALL_FAN = "dead_fire_coral_wall_fan",
    DEAD_HORN_CORAL_WALL_FAN = "dead_horn_coral_wall_fan",
    TUBE_CORAL_WALL_FAN = "tube_coral_wall_fan",
    BRAIN_CORAL_WALL_FAN = "brain_coral_wall_fan",
    BUBBLE_CORAL_WALL_FAN = "bubble_coral_wall_fan",
    FIRE_CORAL_WALL_FAN = "fire_coral_wall_fan",
    HORN_CORAL_WALL_FAN = "horn_coral_wall_fan",
    SEA_PICKLE = "sea_pickle",
    BLUE_ICE = "blue_ice",
    CONDUIT = "conduit",
    BAMBOO_SAPLING = "bamboo_sapling",
    BAMBOO = "bamboo",
    POTTED_BAMBOO = "potted_bamboo",
    VOID_AIR = "void_air",
    CAVE_AIR = "cave_air",
    BUBBLE_COLUMN = "bubble_column",
    POLISHED_GRANITE_STAIRS = "polished_granite_stairs",
    SMOOTH_RED_SANDSTONE_STAIRS = "smooth_red_sandstone_stairs",
    MOSSY_STONE_BRICK_STAIRS = "mossy_stone_brick_stairs",
    POLISHED_DIORITE_STAIRS = "polished_diorite_stairs",
    MOSSY_COBBLESTONE_STAIRS = "mossy_cobblestone_stairs",
    END_STONE_BRICK_STAIRS = "end_stone_brick_stairs",
    STONE_STAIRS = "stone_stairs",
    SMOOTH_SANDSTONE_STAIRS = "smooth_sandstone_stairs",
    SMOOTH_QUARTZ_STAIRS = "smooth_quartz_stairs",
    GRANITE_STAIRS = "granite_stairs",
    ANDESITE_STAIRS = "andesite_stairs",
    RED_NETHER_BRICK_STAIRS = "red_nether_brick_stairs",
    POLISHED_ANDESITE_STAIRS = "polished_andesite_stairs",
    DIORITE_STAIRS = "diorite_stairs",
    POLISHED_GRANITE_SLAB = "polished_granite_slab",
    SMOOTH_RED_SANDSTONE_SLAB = "smooth_red_sandstone_slab",
    MOSSY_STONE_BRICK_SLAB = "mossy_stone_brick_slab",
    POLISHED_DIORITE_SLAB = "polished_diorite_slab",
    MOSSY_COBBLESTONE_SLAB = "mossy_cobblestone_slab",
    END_STONE_BRICK_SLAB = "end_stone_brick_slab",
    SMOOTH_SANDSTONE_SLAB = "smooth_sandstone_slab",
    SMOOTH_QUARTZ_SLAB = "smooth_quartz_slab",
    GRANITE_SLAB = "granite_slab",
    ANDESITE_SLAB = "andesite_slab",
    RED_NETHER_BRICK_SLAB = "red_nether_brick_slab",
    POLISHED_ANDESITE_SLAB = "polished_andesite_slab",
    DIORITE_SLAB = "diorite_slab",
    BRICK_WALL = "brick_wall",
    PRISMARINE_WALL = "prismarine_wall",
    RED_SANDSTONE_WALL = "red_sandstone_wall",
    MOSSY_STONE_BRICK_WALL = "mossy_stone_brick_wall",
    GRANITE_WALL = "granite_wall",
    STONE_BRICK_WALL = "stone_brick_wall",
    NETHER_BRICK_WALL = "nether_brick_wall",
    ANDESITE_WALL = "andesite_wall",
    RED_NETHER_BRICK_WALL = "red_nether_brick_wall",
    SANDSTONE_WALL = "sandstone_wall",
    END_STONE_BRICK_WALL = "end_stone_brick_wall",
    DIORITE_WALL = "diorite_wall",
    SCAFFOLDING = "scaffolding",
    LOOM = "loom",
    BARREL = "barrel",
    SMOKER = "smoker",
    BLAST_FURNACE = "blast_furnace",
    CARTOGRAPHY_TABLE = "cartography_table",
    FLETCHING_TABLE = "fletching_table",
    GRINDSTONE = "grindstone",
    LECTERN = "lectern",
    SMITHING_TABLE = "smithing_table",
    STONECUTTER = "stonecutter",
    BELL = "bell",
    LANTERN = "lantern",
    SOUL_LANTERN = "soul_lantern",
    CAMPFIRE = "campfire",
    SOUL_CAMPFIRE = "soul_campfire",
    SWEET_BERRY_BUSH = "sweet_berry_bush",
    WARPED_STEM = "warped_stem",
    STRIPPED_WARPED_STEM = "stripped_warped_stem",
    WARPED_HYPHAE = "warped_hyphae",
    STRIPPED_WARPED_HYPHAE = "stripped_warped_hyphae",
    WARPED_NYLIUM = "warped_nylium",
    WARPED_FUNGUS = "warped_fungus",
    WARPED_WART_BLOCK = "warped_wart_block",
    WARPED_ROOTS = "warped_roots",
    NETHER_SPROUTS = "nether_sprouts",
    CRIMSON_STEM = "crimson_stem",
    STRIPPED_CRIMSON_STEM = "stripped_crimson_stem",
    CRIMSON_HYPHAE = "crimson_hyphae",
    STRIPPED_CRIMSON_HYPHAE = "stripped_crimson_hyphae",
    CRIMSON_NYLIUM = "crimson_nylium",
    CRIMSON_FUNGUS = "crimson_fungus",
    SHROOMLIGHT = "shroomlight",
    WEEPING_VINES = "weeping_vines",
    WEEPING_VINES_PLANT = "weeping_vines_plant",
    TWISTING_VINES = "twisting_vines",
    TWISTING_VINES_PLANT = "twisting_vines_plant",
    CRIMSON_ROOTS = "crimson_roots",
    CRIMSON_PLANKS = "crimson_planks",
    WARPED_PLANKS = "warped_planks",
    CRIMSON_SLAB = "crimson_slab",
    WARPED_SLAB = "warped_slab",
    CRIMSON_PRESSURE_PLATE = "crimson_pressure_plate",
    WARPED_PRESSURE_PLATE = "warped_pressure_plate",
    CRIMSON_FENCE = "crimson_fence",
    WARPED_FENCE = "warped_fence",
    CRIMSON_TRAPDOOR = "crimson_trapdoor",
    WARPED_TRAPDOOR = "warped_trapdoor",
    CRIMSON_FENCE_GATE = "crimson_fence_gate",
    WARPED_FENCE_GATE = "warped_fence_gate",
    CRIMSON_STAIRS = "crimson_stairs",
    WARPED_STAIRS = "warped_stairs",
    CRIMSON_BUTTON = "crimson_button",
    WARPED_BUTTON = "warped_button",
    CRIMSON_DOOR = "crimson_door",
    WARPED_DOOR = "warped_door",
    CRIMSON_SIGN = "crimson_sign",
    WARPED_SIGN = "warped_sign",
    CRIMSON_WALL_SIGN = "crimson_wall_sign",
    WARPED_WALL_SIGN = "warped_wall_sign",
    STRUCTURE_BLOCK = "structure_block",
    JIGSAW = "jigsaw",
    COMPOSTER = "composter",
    TARGET = "target",
    BEE_NEST = "bee_nest",
    BEEHIVE = "beehive",
    HONEY_BLOCK = "honey_block",
    HONEYCOMB_BLOCK = "honeycomb_block",
    NETHERITE_BLOCK = "netherite_block",
    ANCIENT_DEBRIS = "ancient_debris",
    CRYING_OBSIDIAN = "crying_obsidian",
    RESPAWN_ANCHOR = "respawn_anchor",
    POTTED_CRIMSON_FUNGUS = "potted_crimson_fungus",
    POTTED_WARPED_FUNGUS = "potted_warped_fungus",
    POTTED_CRIMSON_ROOTS = "potted_crimson_roots",
    POTTED_WARPED_ROOTS = "potted_warped_roots",
    LODESTONE = "lodestone",
    BLACKSTONE = "blackstone",
    BLACKSTONE_STAIRS = "blackstone_stairs",
    BLACKSTONE_WALL = "blackstone_wall",
    BLACKSTONE_SLAB = "blackstone_slab",
    POLISHED_BLACKSTONE = "polished_blackstone",
    POLISHED_BLACKSTONE_BRICKS = "polished_blackstone_bricks",
    CRACKED_POLISHED_BLACKSTONE_BRICKS = "cracked_polished_blackstone_bricks",
    CHISELED_POLISHED_BLACKSTONE = "chiseled_polished_blackstone",
    POLISHED_BLACKSTONE_BRICK_SLAB = "polished_blackstone_brick_slab",
    POLISHED_BLACKSTONE_BRICK_STAIRS = "polished_blackstone_brick_stairs",
    POLISHED_BLACKSTONE_BRICK_WALL = "polished_blackstone_brick_wall",
    GILDED_BLACKSTONE = "gilded_blackstone",
    POLISHED_BLACKSTONE_STAIRS = "polished_blackstone_stairs",
    POLISHED_BLACKSTONE_SLAB = "polished_blackstone_slab",
    POLISHED_BLACKSTONE_PRESSURE_PLATE = "polished_blackstone_pressure_plate",
    POLISHED_BLACKSTONE_BUTTON = "polished_blackstone_button",
    POLISHED_BLACKSTONE_WALL = "polished_blackstone_wall",
    CHISELED_NETHER_BRICKS = "chiseled_nether_bricks",
    CRACKED_NETHER_BRICKS = "cracked_nether_bricks",
    QUARTZ_BRICKS = "quartz_bricks",
    CANDLE = "candle",
    WHITE_CANDLE = "white_candle",
    ORANGE_CANDLE = "orange_candle",
    MAGENTA_CANDLE = "magenta_candle",
    LIGHT_BLUE_CANDLE = "light_blue_candle",
    YELLOW_CANDLE = "yellow_candle",
    LIME_CANDLE = "lime_candle",
    PINK_CANDLE = "pink_candle",
    GRAY_CANDLE = "gray_candle",
    LIGHT_GRAY_CANDLE = "light_gray_candle",
    CYAN_CANDLE = "cyan_candle",
    PURPLE_CANDLE = "purple_candle",
    BLUE_CANDLE = "blue_candle",
    BROWN_CANDLE = "brown_candle",
    GREEN_CANDLE = "green_candle",
    RED_CANDLE = "red_candle",
    BLACK_CANDLE = "black_candle",
    CANDLE_CAKE = "candle_cake",
    WHITE_CANDLE_CAKE = "white_candle_cake",
    ORANGE_CANDLE_CAKE = "orange_candle_cake",
    MAGENTA_CANDLE_CAKE = "magenta_candle_cake",
    LIGHT_BLUE_CANDLE_CAKE = "light_blue_candle_cake",
    YELLOW_CANDLE_CAKE = "yellow_candle_cake",
    LIME_CANDLE_CAKE = "lime_candle_cake",
    PINK_CANDLE_CAKE = "pink_candle_cake",
    GRAY_CANDLE_CAKE = "gray_candle_cake",
    LIGHT_GRAY_CANDLE_CAKE = "light_gray_candle_cake",
    CYAN_CANDLE_CAKE = "cyan_candle_cake",
    PURPLE_CANDLE_CAKE = "purple_candle_cake",
    BLUE_CANDLE_CAKE = "blue_candle_cake",
    BROWN_CANDLE_CAKE = "brown_candle_cake",
    GREEN_CANDLE_CAKE = "green_candle_cake",
    RED_CANDLE_CAKE = "red_candle_cake",
    BLACK_CANDLE_CAKE = "black_candle_cake",
    AMETHYST_BLOCK = "amethyst_block",
    BUDDING_AMETHYST = "budding_amethyst",
    AMETHYST_CLUSTER = "amethyst_cluster",
    LARGE_AMETHYST_BUD = "large_amethyst_bud",
    MEDIUM_AMETHYST_BUD = "medium_amethyst_bud",
    SMALL_AMETHYST_BUD = "small_amethyst_bud",
    TUFF = "tuff",
    CALCITE = "calcite",
    TINTED_GLASS = "tinted_glass",
    POWDER_SNOW = "powder_snow",
    SCULK_SENSOR = "sculk_sensor",
    OXIDIZED_COPPER = "oxidized_copper",
    WEATHERED_COPPER = "weathered_copper",
    EXPOSED_COPPER = "exposed_copper",
    COPPER_BLOCK = "copper_block",
    COPPER_ORE = "copper_ore",
    DEEPSLATE_COPPER_ORE = "deepslate_copper_ore",
    OXIDIZED_CUT_COPPER = "oxidized_cut_copper",
    WEATHERED_CUT_COPPER = "weathered_cut_copper",
    EXPOSED_CUT_COPPER = "exposed_cut_copper",
    CUT_COPPER = "cut_copper",
    OXIDIZED_CUT_COPPER_STAIRS = "oxidized_cut_copper_stairs",
    WEATHERED_CUT_COPPER_STAIRS = "weathered_cut_copper_stairs",
    EXPOSED_CUT_COPPER_STAIRS = "exposed_cut_copper_stairs",
    CUT_COPPER_STAIRS = "cut_copper_stairs",
    OXIDIZED_CUT_COPPER_SLAB = "oxidized_cut_copper_slab",
    WEATHERED_CUT_COPPER_SLAB = "weathered_cut_copper_slab",
    EXPOSED_CUT_COPPER_SLAB = "exposed_cut_copper_slab",
    CUT_COPPER_SLAB = "cut_copper_slab",
    WAXED_COPPER_BLOCK = "waxed_copper_block",
    WAXED_WEATHERED_COPPER = "waxed_weathered_copper",
    WAXED_EXPOSED_COPPER = "waxed_exposed_copper",
    WAXED_OXIDIZED_COPPER = "waxed_oxidized_copper",
    WAXED_OXIDIZED_CUT_COPPER = "waxed_oxidized_cut_copper",
    WAXED_WEATHERED_CUT_COPPER = "waxed_weathered_cut_copper",
    WAXED_EXPOSED_CUT_COPPER = "waxed_exposed_cut_copper",
    WAXED_CUT_COPPER = "waxed_cut_copper",
    WAXED_OXIDIZED_CUT_COPPER_STAIRS = "waxed_oxidized_cut_copper_stairs",
    WAXED_WEATHERED_CUT_COPPER_STAIRS = "waxed_weathered_cut_copper_stairs",
    WAXED_EXPOSED_CUT_COPPER_STAIRS = "waxed_exposed_cut_copper_stairs",
    WAXED_CUT_COPPER_STAIRS = "waxed_cut_copper_stairs",
    WAXED_OXIDIZED_CUT_COPPER_SLAB = "waxed_oxidized_cut_copper_slab",
    WAXED_WEATHERED_CUT_COPPER_SLAB = "waxed_weathered_cut_copper_slab",
    WAXED_EXPOSED_CUT_COPPER_SLAB = "waxed_exposed_cut_copper_slab",
    WAXED_CUT_COPPER_SLAB = "waxed_cut_copper_slab",
    LIGHTNING_ROD = "lightning_rod",
    POINTED_DRIPSTONE = "pointed_dripstone",
    DRIPSTONE_BLOCK = "dripstone_block",
    CAVE_VINES = "cave_vines",
    CAVE_VINES_PLANT = "cave_vines_plant",
    SPORE_BLOSSOM = "spore_blossom",
    AZALEA = "azalea",
    FLOWERING_AZALEA = "flowering_azalea",
    MOSS_CARPET = "moss_carpet",
    MOSS_BLOCK = "moss_block",
    BIG_DRIPLEAF = "big_dripleaf",
    BIG_DRIPLEAF_STEM = "big_dripleaf_stem",
    SMALL_DRIPLEAF = "small_dripleaf",
    HANGING_ROOTS = "hanging_roots",
    ROOTED_DIRT = "rooted_dirt",
    DEEPSLATE = "deepslate",
    COBBLED_DEEPSLATE = "cobbled_deepslate",
    COBBLED_DEEPSLATE_STAIRS = "cobbled_deepslate_stairs",
    COBBLED_DEEPSLATE_SLAB = "cobbled_deepslate_slab",
    COBBLED_DEEPSLATE_WALL = "cobbled_deepslate_wall",
    POLISHED_DEEPSLATE = "polished_deepslate",
    POLISHED_DEEPSLATE_STAIRS = "polished_deepslate_stairs",
    POLISHED_DEEPSLATE_SLAB = "polished_deepslate_slab",
    POLISHED_DEEPSLATE_WALL = "polished_deepslate_wall",
    DEEPSLATE_TILES = "deepslate_tiles",
    DEEPSLATE_TILE_STAIRS = "deepslate_tile_stairs",
    DEEPSLATE_TILE_SLAB = "deepslate_tile_slab",
    DEEPSLATE_TILE_WALL = "deepslate_tile_wall",
    DEEPSLATE_BRICKS = "deepslate_bricks",
    DEEPSLATE_BRICK_STAIRS = "deepslate_brick_stairs",
    DEEPSLATE_BRICK_SLAB = "deepslate_brick_slab",
    DEEPSLATE_BRICK_WALL = "deepslate_brick_wall",
    CHISELED_DEEPSLATE = "chiseled_deepslate",
    CRACKED_DEEPSLATE_BRICKS = "cracked_deepslate_bricks",
    CRACKED_DEEPSLATE_TILES = "cracked_deepslate_tiles",
    INFESTED_DEEPSLATE = "infested_deepslate",
    SMOOTH_BASALT = "smooth_basalt",
    RAW_IRON_BLOCK = "raw_iron_block",
    RAW_COPPER_BLOCK = "raw_copper_block",
    RAW_GOLD_BLOCK = "raw_gold_block",
    POTTED_AZALEA = "potted_azalea_bush",
    POTTED_FLOWERING_AZALEA = "potted_flowering_azalea_bush",
}

export const CPP_ID_TO_BLOCK_NAME = [
    null,
    "air",
    "stone",
    "granite",
    "polished_granite",
    "diorite",
    "polished_diorite",
    "andesite",
    "polished_andesite",
    "grass_block",
    "dirt",
    "coarse_dirt",
    "podzol",
    "cobblestone",
    "oak_planks",
    "spruce_planks",
    "birch_planks",
    "jungle_planks",
    "acacia_planks",
    "dark_oak_planks",
    "oak_sapling",
    "spruce_sapling",
    "birch_sapling",
    "jungle_sapling",
    "acacia_sapling",
    "dark_oak_sapling",
    "bedrock",
    "water",
    "lava",
    "sand",
    "red_sand",
    "gravel",
    "gold_ore",
    "deepslate_gold_ore",
    "iron_ore",
    "deepslate_iron_ore",
    "coal_ore",
    "deepslate_coal_ore",
    "nether_gold_ore",
    "oak_log",
    "spruce_log",
    "birch_log",
    "jungle_log",
    "acacia_log",
    "dark_oak_log",
    "stripped_spruce_log",
    "stripped_birch_log",
    "stripped_jungle_log",
    "stripped_acacia_log",
    "stripped_dark_oak_log",
    "stripped_oak_log",
    "oak_wood",
    "spruce_wood",
    "birch_wood",
    "jungle_wood",
    "acacia_wood",
    "dark_oak_wood",
    "stripped_oak_wood",
    "stripped_spruce_wood",
    "stripped_birch_wood",
    "stripped_jungle_wood",
    "stripped_acacia_wood",
    "stripped_dark_oak_wood",
    "oak_leaves",
    "spruce_leaves",
    "birch_leaves",
    "jungle_leaves",
    "acacia_leaves",
    "dark_oak_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "sponge",
    "wet_sponge",
    "glass",
    "lapis_ore",
    "deepslate_lapis_ore",
    "lapis_block",
    "dispenser",
    "sandstone",
    "chiseled_sandstone",
    "cut_sandstone",
    "note_block",
    "white_bed",
    "orange_bed",
    "magenta_bed",
    "light_blue_bed",
    "yellow_bed",
    "lime_bed",
    "pink_bed",
    "gray_bed",
    "light_gray_bed",
    "cyan_bed",
    "purple_bed",
    "blue_bed",
    "brown_bed",
    "green_bed",
    "red_bed",
    "black_bed",
    "powered_rail",
    "detector_rail",
    "sticky_piston",
    "cobweb",
    "grass",
    "fern",
    "dead_bush",
    "seagrass",
    "tall_seagrass",
    "piston",
    "piston_head",
    "white_wool",
    "orange_wool",
    "magenta_wool",
    "light_blue_wool",
    "yellow_wool",
    "lime_wool",
    "pink_wool",
    "gray_wool",
    "light_gray_wool",
    "cyan_wool",
    "purple_wool",
    "blue_wool",
    "brown_wool",
    "green_wool",
    "red_wool",
    "black_wool",
    "moving_piston",
    "dandelion",
    "poppy",
    "blue_orchid",
    "allium",
    "azure_bluet",
    "red_tulip",
    "orange_tulip",
    "white_tulip",
    "pink_tulip",
    "oxeye_daisy",
    "cornflower",
    "wither_rose",
    "lily_of_the_valley",
    "brown_mushroom",
    "red_mushroom",
    "gold_block",
    "iron_block",
    "bricks",
    "tnt",
    "bookshelf",
    "mossy_cobblestone",
    "obsidian",
    "torch",
    "wall_torch",
    "fire",
    "soul_fire",
    "spawner",
    "oak_stairs",
    "chest",
    "redstone_wire",
    "diamond_ore",
    "deepslate_diamond_ore",
    "diamond_block",
    "crafting_table",
    "wheat",
    "farmland",
    "furnace",
    "oak_sign",
    "spruce_sign",
    "birch_sign",
    "acacia_sign",
    "jungle_sign",
    "dark_oak_sign",
    "oak_door",
    "ladder",
    "rail",
    "cobblestone_stairs",
    "oak_wall_sign",
    "spruce_wall_sign",
    "birch_wall_sign",
    "acacia_wall_sign",
    "jungle_wall_sign",
    "dark_oak_wall_sign",
    "lever",
    "stone_pressure_plate",
    "iron_door",
    "oak_pressure_plate",
    "spruce_pressure_plate",
    "birch_pressure_plate",
    "jungle_pressure_plate",
    "acacia_pressure_plate",
    "dark_oak_pressure_plate",
    "redstone_ore",
    "deepslate_redstone_ore",
    "redstone_torch",
    "redstone_wall_torch",
    "stone_button",
    "snow",
    "ice",
    "snow_block",
    "cactus",
    "clay",
    "sugar_cane",
    "jukebox",
    "oak_fence",
    "pumpkin",
    "netherrack",
    "soul_sand",
    "soul_soil",
    "basalt",
    "polished_basalt",
    "soul_torch",
    "soul_wall_torch",
    "glowstone",
    "nether_portal",
    "carved_pumpkin",
    "jack_o_lantern",
    "cake",
    "repeater",
    "white_stained_glass",
    "orange_stained_glass",
    "magenta_stained_glass",
    "light_blue_stained_glass",
    "yellow_stained_glass",
    "lime_stained_glass",
    "pink_stained_glass",
    "gray_stained_glass",
    "light_gray_stained_glass",
    "cyan_stained_glass",
    "purple_stained_glass",
    "blue_stained_glass",
    "brown_stained_glass",
    "green_stained_glass",
    "red_stained_glass",
    "black_stained_glass",
    "oak_trapdoor",
    "spruce_trapdoor",
    "birch_trapdoor",
    "jungle_trapdoor",
    "acacia_trapdoor",
    "dark_oak_trapdoor",
    "stone_bricks",
    "mossy_stone_bricks",
    "cracked_stone_bricks",
    "chiseled_stone_bricks",
    "infested_stone",
    "infested_cobblestone",
    "infested_stone_bricks",
    "infested_mossy_stone_bricks",
    "infested_cracked_stone_bricks",
    "infested_chiseled_stone_bricks",
    "brown_mushroom_block",
    "red_mushroom_block",
    "mushroom_stem",
    "iron_bars",
    "chain",
    "glass_pane",
    "melon",
    "attached_pumpkin_stem",
    "attached_melon_stem",
    "pumpkin_stem",
    "melon_stem",
    "vine",
    "glow_lichen",
    "oak_fence_gate",
    "brick_stairs",
    "stone_brick_stairs",
    "mycelium",
    "lily_pad",
    "nether_bricks",
    "nether_brick_fence",
    "nether_brick_stairs",
    "nether_wart",
    "enchanting_table",
    "brewing_stand",
    "cauldron",
    "water_cauldron",
    "lava_cauldron",
    "powder_snow_cauldron",
    "end_portal",
    "end_portal_frame",
    "end_stone",
    "dragon_egg",
    "redstone_lamp",
    "cocoa",
    "sandstone_stairs",
    "emerald_ore",
    "deepslate_emerald_ore",
    "ender_chest",
    "tripwire_hook",
    "tripwire",
    "emerald_block",
    "spruce_stairs",
    "birch_stairs",
    "jungle_stairs",
    "command_block",
    "beacon",
    "cobblestone_wall",
    "mossy_cobblestone_wall",
    "flower_pot",
    "potted_oak_sapling",
    "potted_spruce_sapling",
    "potted_birch_sapling",
    "potted_jungle_sapling",
    "potted_acacia_sapling",
    "potted_dark_oak_sapling",
    "potted_fern",
    "potted_dandelion",
    "potted_poppy",
    "potted_blue_orchid",
    "potted_allium",
    "potted_azure_bluet",
    "potted_red_tulip",
    "potted_orange_tulip",
    "potted_white_tulip",
    "potted_pink_tulip",
    "potted_oxeye_daisy",
    "potted_cornflower",
    "potted_lily_of_the_valley",
    "potted_wither_rose",
    "potted_red_mushroom",
    "potted_brown_mushroom",
    "potted_dead_bush",
    "potted_cactus",
    "carrots",
    "potatoes",
    "oak_button",
    "spruce_button",
    "birch_button",
    "jungle_button",
    "acacia_button",
    "dark_oak_button",
    "skeleton_skull",
    "skeleton_wall_skull",
    "wither_skeleton_skull",
    "wither_skeleton_wall_skull",
    "zombie_head",
    "zombie_wall_head",
    "player_head",
    "player_wall_head",
    "creeper_head",
    "creeper_wall_head",
    "dragon_head",
    "dragon_wall_head",
    "anvil",
    "chipped_anvil",
    "damaged_anvil",
    "trapped_chest",
    "light_weighted_pressure_plate",
    "heavy_weighted_pressure_plate",
    "comparator",
    "daylight_detector",
    "redstone_block",
    "nether_quartz_ore",
    "hopper",
    "quartz_block",
    "chiseled_quartz_block",
    "quartz_pillar",
    "quartz_stairs",
    "activator_rail",
    "dropper",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "white_stained_glass_pane",
    "orange_stained_glass_pane",
    "magenta_stained_glass_pane",
    "light_blue_stained_glass_pane",
    "yellow_stained_glass_pane",
    "lime_stained_glass_pane",
    "pink_stained_glass_pane",
    "gray_stained_glass_pane",
    "light_gray_stained_glass_pane",
    "cyan_stained_glass_pane",
    "purple_stained_glass_pane",
    "blue_stained_glass_pane",
    "brown_stained_glass_pane",
    "green_stained_glass_pane",
    "red_stained_glass_pane",
    "black_stained_glass_pane",
    "acacia_stairs",
    "dark_oak_stairs",
    "slime_block",
    "barrier",
    "light",
    "iron_trapdoor",
    "prismarine",
    "prismarine_bricks",
    "dark_prismarine",
    "prismarine_stairs",
    "prismarine_brick_stairs",
    "dark_prismarine_stairs",
    "prismarine_slab",
    "prismarine_brick_slab",
    "dark_prismarine_slab",
    "sea_lantern",
    "hay_block",
    "white_carpet",
    "orange_carpet",
    "magenta_carpet",
    "light_blue_carpet",
    "yellow_carpet",
    "lime_carpet",
    "pink_carpet",
    "gray_carpet",
    "light_gray_carpet",
    "cyan_carpet",
    "purple_carpet",
    "blue_carpet",
    "brown_carpet",
    "green_carpet",
    "red_carpet",
    "black_carpet",
    "terracotta",
    "coal_block",
    "packed_ice",
    "sunflower",
    "lilac",
    "rose_bush",
    "peony",
    "tall_grass",
    "large_fern",
    "white_banner",
    "orange_banner",
    "magenta_banner",
    "light_blue_banner",
    "yellow_banner",
    "lime_banner",
    "pink_banner",
    "gray_banner",
    "light_gray_banner",
    "cyan_banner",
    "purple_banner",
    "blue_banner",
    "brown_banner",
    "green_banner",
    "red_banner",
    "black_banner",
    "white_wall_banner",
    "orange_wall_banner",
    "magenta_wall_banner",
    "light_blue_wall_banner",
    "yellow_wall_banner",
    "lime_wall_banner",
    "pink_wall_banner",
    "gray_wall_banner",
    "light_gray_wall_banner",
    "cyan_wall_banner",
    "purple_wall_banner",
    "blue_wall_banner",
    "brown_wall_banner",
    "green_wall_banner",
    "red_wall_banner",
    "black_wall_banner",
    "red_sandstone",
    "chiseled_red_sandstone",
    "cut_red_sandstone",
    "red_sandstone_stairs",
    "oak_slab",
    "spruce_slab",
    "birch_slab",
    "jungle_slab",
    "acacia_slab",
    "dark_oak_slab",
    "stone_slab",
    "smooth_stone_slab",
    "sandstone_slab",
    "cut_sandstone_slab",
    "petrified_oak_slab",
    "cobblestone_slab",
    "brick_slab",
    "stone_brick_slab",
    "nether_brick_slab",
    "quartz_slab",
    "red_sandstone_slab",
    "cut_red_sandstone_slab",
    "purpur_slab",
    "smooth_stone",
    "smooth_sandstone",
    "smooth_quartz",
    "smooth_red_sandstone",
    "spruce_fence_gate",
    "birch_fence_gate",
    "jungle_fence_gate",
    "acacia_fence_gate",
    "dark_oak_fence_gate",
    "spruce_fence",
    "birch_fence",
    "jungle_fence",
    "acacia_fence",
    "dark_oak_fence",
    "spruce_door",
    "birch_door",
    "jungle_door",
    "acacia_door",
    "dark_oak_door",
    "end_rod",
    "chorus_plant",
    "chorus_flower",
    "purpur_block",
    "purpur_pillar",
    "purpur_stairs",
    "end_stone_bricks",
    "beetroots",
    "dirt_path",
    "end_gateway",
    "repeating_command_block",
    "chain_command_block",
    "frosted_ice",
    "magma_block",
    "nether_wart_block",
    "red_nether_bricks",
    "bone_block",
    "structure_void",
    "observer",
    "shulker_box",
    "white_shulker_box",
    "orange_shulker_box",
    "magenta_shulker_box",
    "light_blue_shulker_box",
    "yellow_shulker_box",
    "lime_shulker_box",
    "pink_shulker_box",
    "gray_shulker_box",
    "light_gray_shulker_box",
    "cyan_shulker_box",
    "purple_shulker_box",
    "blue_shulker_box",
    "brown_shulker_box",
    "green_shulker_box",
    "red_shulker_box",
    "black_shulker_box",
    "white_glazed_terracotta",
    "orange_glazed_terracotta",
    "magenta_glazed_terracotta",
    "light_blue_glazed_terracotta",
    "yellow_glazed_terracotta",
    "lime_glazed_terracotta",
    "pink_glazed_terracotta",
    "gray_glazed_terracotta",
    "light_gray_glazed_terracotta",
    "cyan_glazed_terracotta",
    "purple_glazed_terracotta",
    "blue_glazed_terracotta",
    "brown_glazed_terracotta",
    "green_glazed_terracotta",
    "red_glazed_terracotta",
    "black_glazed_terracotta",
    "white_concrete",
    "orange_concrete",
    "magenta_concrete",
    "light_blue_concrete",
    "yellow_concrete",
    "lime_concrete",
    "pink_concrete",
    "gray_concrete",
    "light_gray_concrete",
    "cyan_concrete",
    "purple_concrete",
    "blue_concrete",
    "brown_concrete",
    "green_concrete",
    "red_concrete",
    "black_concrete",
    "white_concrete_powder",
    "orange_concrete_powder",
    "magenta_concrete_powder",
    "light_blue_concrete_powder",
    "yellow_concrete_powder",
    "lime_concrete_powder",
    "pink_concrete_powder",
    "gray_concrete_powder",
    "light_gray_concrete_powder",
    "cyan_concrete_powder",
    "purple_concrete_powder",
    "blue_concrete_powder",
    "brown_concrete_powder",
    "green_concrete_powder",
    "red_concrete_powder",
    "black_concrete_powder",
    "kelp",
    "kelp_plant",
    "dried_kelp_block",
    "turtle_egg",
    "dead_tube_coral_block",
    "dead_brain_coral_block",
    "dead_bubble_coral_block",
    "dead_fire_coral_block",
    "dead_horn_coral_block",
    "tube_coral_block",
    "brain_coral_block",
    "bubble_coral_block",
    "fire_coral_block",
    "horn_coral_block",
    "dead_tube_coral",
    "dead_brain_coral",
    "dead_bubble_coral",
    "dead_fire_coral",
    "dead_horn_coral",
    "tube_coral",
    "brain_coral",
    "bubble_coral",
    "fire_coral",
    "horn_coral",
    "dead_tube_coral_fan",
    "dead_brain_coral_fan",
    "dead_bubble_coral_fan",
    "dead_fire_coral_fan",
    "dead_horn_coral_fan",
    "tube_coral_fan",
    "brain_coral_fan",
    "bubble_coral_fan",
    "fire_coral_fan",
    "horn_coral_fan",
    "dead_tube_coral_wall_fan",
    "dead_brain_coral_wall_fan",
    "dead_bubble_coral_wall_fan",
    "dead_fire_coral_wall_fan",
    "dead_horn_coral_wall_fan",
    "tube_coral_wall_fan",
    "brain_coral_wall_fan",
    "bubble_coral_wall_fan",
    "fire_coral_wall_fan",
    "horn_coral_wall_fan",
    "sea_pickle",
    "blue_ice",
    "conduit",
    "bamboo_sapling",
    "bamboo",
    "potted_bamboo",
    "void_air",
    "cave_air",
    "bubble_column",
    "polished_granite_stairs",
    "smooth_red_sandstone_stairs",
    "mossy_stone_brick_stairs",
    "polished_diorite_stairs",
    "mossy_cobblestone_stairs",
    "end_stone_brick_stairs",
    "stone_stairs",
    "smooth_sandstone_stairs",
    "smooth_quartz_stairs",
    "granite_stairs",
    "andesite_stairs",
    "red_nether_brick_stairs",
    "polished_andesite_stairs",
    "diorite_stairs",
    "polished_granite_slab",
    "smooth_red_sandstone_slab",
    "mossy_stone_brick_slab",
    "polished_diorite_slab",
    "mossy_cobblestone_slab",
    "end_stone_brick_slab",
    "smooth_sandstone_slab",
    "smooth_quartz_slab",
    "granite_slab",
    "andesite_slab",
    "red_nether_brick_slab",
    "polished_andesite_slab",
    "diorite_slab",
    "brick_wall",
    "prismarine_wall",
    "red_sandstone_wall",
    "mossy_stone_brick_wall",
    "granite_wall",
    "stone_brick_wall",
    "nether_brick_wall",
    "andesite_wall",
    "red_nether_brick_wall",
    "sandstone_wall",
    "end_stone_brick_wall",
    "diorite_wall",
    "scaffolding",
    "loom",
    "barrel",
    "smoker",
    "blast_furnace",
    "cartography_table",
    "fletching_table",
    "grindstone",
    "lectern",
    "smithing_table",
    "stonecutter",
    "bell",
    "lantern",
    "soul_lantern",
    "campfire",
    "soul_campfire",
    "sweet_berry_bush",
    "warped_stem",
    "stripped_warped_stem",
    "warped_hyphae",
    "stripped_warped_hyphae",
    "warped_nylium",
    "warped_fungus",
    "warped_wart_block",
    "warped_roots",
    "nether_sprouts",
    "crimson_stem",
    "stripped_crimson_stem",
    "crimson_hyphae",
    "stripped_crimson_hyphae",
    "crimson_nylium",
    "crimson_fungus",
    "shroomlight",
    "weeping_vines",
    "weeping_vines_plant",
    "twisting_vines",
    "twisting_vines_plant",
    "crimson_roots",
    "crimson_planks",
    "warped_planks",
    "crimson_slab",
    "warped_slab",
    "crimson_pressure_plate",
    "warped_pressure_plate",
    "crimson_fence",
    "warped_fence",
    "crimson_trapdoor",
    "warped_trapdoor",
    "crimson_fence_gate",
    "warped_fence_gate",
    "crimson_stairs",
    "warped_stairs",
    "crimson_button",
    "warped_button",
    "crimson_door",
    "warped_door",
    "crimson_sign",
    "warped_sign",
    "crimson_wall_sign",
    "warped_wall_sign",
    "structure_block",
    "jigsaw",
    "composter",
    "target",
    "bee_nest",
    "beehive",
    "honey_block",
    "honeycomb_block",
    "netherite_block",
    "ancient_debris",
    "crying_obsidian",
    "respawn_anchor",
    "potted_crimson_fungus",
    "potted_warped_fungus",
    "potted_crimson_roots",
    "potted_warped_roots",
    "lodestone",
    "blackstone",
    "blackstone_stairs",
    "blackstone_wall",
    "blackstone_slab",
    "polished_blackstone",
    "polished_blackstone_bricks",
    "cracked_polished_blackstone_bricks",
    "chiseled_polished_blackstone",
    "polished_blackstone_brick_slab",
    "polished_blackstone_brick_stairs",
    "polished_blackstone_brick_wall",
    "gilded_blackstone",
    "polished_blackstone_stairs",
    "polished_blackstone_slab",
    "polished_blackstone_pressure_plate",
    "polished_blackstone_button",
    "polished_blackstone_wall",
    "chiseled_nether_bricks",
    "cracked_nether_bricks",
    "quartz_bricks",
    "candle",
    "white_candle",
    "orange_candle",
    "magenta_candle",
    "light_blue_candle",
    "yellow_candle",
    "lime_candle",
    "pink_candle",
    "gray_candle",
    "light_gray_candle",
    "cyan_candle",
    "purple_candle",
    "blue_candle",
    "brown_candle",
    "green_candle",
    "red_candle",
    "black_candle",
    "candle_cake",
    "white_candle_cake",
    "orange_candle_cake",
    "magenta_candle_cake",
    "light_blue_candle_cake",
    "yellow_candle_cake",
    "lime_candle_cake",
    "pink_candle_cake",
    "gray_candle_cake",
    "light_gray_candle_cake",
    "cyan_candle_cake",
    "purple_candle_cake",
    "blue_candle_cake",
    "brown_candle_cake",
    "green_candle_cake",
    "red_candle_cake",
    "black_candle_cake",
    "amethyst_block",
    "budding_amethyst",
    "amethyst_cluster",
    "large_amethyst_bud",
    "medium_amethyst_bud",
    "small_amethyst_bud",
    "tuff",
    "calcite",
    "tinted_glass",
    "powder_snow",
    "sculk_sensor",
    "oxidized_copper",
    "weathered_copper",
    "exposed_copper",
    "copper_block",
    "copper_ore",
    "deepslate_copper_ore",
    "oxidized_cut_copper",
    "weathered_cut_copper",
    "exposed_cut_copper",
    "cut_copper",
    "oxidized_cut_copper_stairs",
    "weathered_cut_copper_stairs",
    "exposed_cut_copper_stairs",
    "cut_copper_stairs",
    "oxidized_cut_copper_slab",
    "weathered_cut_copper_slab",
    "exposed_cut_copper_slab",
    "cut_copper_slab",
    "waxed_copper_block",
    "waxed_weathered_copper",
    "waxed_exposed_copper",
    "waxed_oxidized_copper",
    "waxed_oxidized_cut_copper",
    "waxed_weathered_cut_copper",
    "waxed_exposed_cut_copper",
    "waxed_cut_copper",
    "waxed_oxidized_cut_copper_stairs",
    "waxed_weathered_cut_copper_stairs",
    "waxed_exposed_cut_copper_stairs",
    "waxed_cut_copper_stairs",
    "waxed_oxidized_cut_copper_slab",
    "waxed_weathered_cut_copper_slab",
    "waxed_exposed_cut_copper_slab",
    "waxed_cut_copper_slab",
    "lightning_rod",
    "pointed_dripstone",
    "dripstone_block",
    "cave_vines",
    "cave_vines_plant",
    "spore_blossom",
    "azalea",
    "flowering_azalea",
    "moss_carpet",
    "moss_block",
    "big_dripleaf",
    "big_dripleaf_stem",
    "small_dripleaf",
    "hanging_roots",
    "rooted_dirt",
    "deepslate",
    "cobbled_deepslate",
    "cobbled_deepslate_stairs",
    "cobbled_deepslate_slab",
    "cobbled_deepslate_wall",
    "polished_deepslate",
    "polished_deepslate_stairs",
    "polished_deepslate_slab",
    "polished_deepslate_wall",
    "deepslate_tiles",
    "deepslate_tile_stairs",
    "deepslate_tile_slab",
    "deepslate_tile_wall",
    "deepslate_bricks",
    "deepslate_brick_stairs",
    "deepslate_brick_slab",
    "deepslate_brick_wall",
    "chiseled_deepslate",
    "cracked_deepslate_bricks",
    "cracked_deepslate_tiles",
    "infested_deepslate",
    "smooth_basalt",
    "raw_iron_block",
    "raw_copper_block",
    "raw_gold_block",
    "potted_azalea_bush",
    "potted_flowering_azalea_bush",
]
